name: animal_switcher
description: A simple Flutter application using the Cubit pattern for state management that switches between displaying a Cat and a Dog when the text is clicked.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true